In [21]:
import pandas as pd
import numpy as np

data = pd.read_csv("data_files/CameraLocs.csv",index_col=0)
scale_columns = ['x','y','z']
for col in scale_columns:
    data[col] = data[col] * 10
data['xr'] = data['xr'] * 0
data.to_csv('data_files/ScaledLocs.csv')
data.head(6)

              x         y       z  xr  yr        zr
frame
1     -45.01910 -18.26810  21.248   0   0  173.4930
2     -28.55930 -11.93800  21.248   0   0  167.0320
3     -58.83100  -5.88361  21.248   0   0  179.8480
4     -10.04920 -31.99800  21.248   0   0  101.5520
5      -7.52653 -53.18820  21.248   0   0   94.7091
6     -45.02980  -5.25799  21.248   0   0  173.9320